### ISSUE TITLE
Support ARG

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#1493]
#### What would you like to be added:
Supoort ARG in ccm
ARG: https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview

**Comment by lzhecheng** [comment]
remove-lifecycle stale

**Comment by lzhecheng** [comment]
/remove-lifecycle rotten
Will need to add options to 1) shorter cache time; 2) decide if cache is enabled.

**Comment by gcampbell12** [comment]
@feiskyer do you know what the plans are with regards to supporting resource graph here? I think that would go a long way to addressing some of the issues I mentioned in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4535 since with flex vmss we could query ARG with the node name (computer name) instead of traversing all the VMSS’s. I’d be happy to volunteer myself.

**Comment by lzhecheng** [comment]
/close
Work on cloud provider side is basically done.
