### ISSUE TITLE
Cloud Node Manager in CrashloopBackoff

### ISSUE THREAD

**Issue by himanshuz2** [kubernetes-sigs/cloud-provider-azure#1807]
#### What happened:
Deployed the Azure Cloud Provider
helm install --repo https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo cloud-provider-azure --generate-name --set infra.clusterName=${CLUSTER_NAME}

cloud-node-manager-windows-n4hks 0/1 CrashLoopBackOff 38 (3h8m ago)

#### What you expected to happen:
cloud-node-manager-windows runs without CrashLoopBackOff
#### How to reproduce it (as minimally and precisely as possible):
Create a capz cluster with windows node and deploy the cloud provider as per this
https://capz.sigs.k8s.io/topics/cloud-provider-config.html

#### Anything else we need to know?:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2349

#### Environment:

- Kubernetes version (use `kubectl version`): 1.23.6
- Cloud provider or hardware configuration: CAPZ 1.3.1 Azure
- OS (e.g: `cat /etc/os-release`):Windows 2019 node
- Kernel (e.g. `uname -a`): Linux CAPZ-Management 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: CAPZ 1.3.1
- Network plugin and version (if this is a network-related bug):  Calico Windows
- Others:

**Comment by MartinForReal** [comment]
I'm wondering if service cidr is changed, Could you please provide kubeconfig file for node manager as described here https://github.com/kubernetes-sigs/cloud-provider-azure/blob/832999275a2876ed3521e3da4f39b30ffa877717/helm/cloud-provider-azure/values.yaml#L55 ?

**Comment by himanshuz2** [comment]
I haven't preserved the cluster to reproduce this problem. I will update when I get a chance to try it again. Why would service cidr change when I deploy the cluster using CAPZ and immediately deploy the cloud provider after that.  CAPZ should have added the correct kubeconfig file on the windows node at the time of deployment because windows node is shown as joined to the cluster.  If capz is not adding the kubeconfig file then the cloud provider helm chart should not rely on it to get the values it needs.

**Comment by rahulgupta999** [comment]
Re-opening this issue. I am facing this issue with the following error:
`Running C:\hpc\/cloud-node-manager.exe  --node-name=cxp-workl-p5szn --use-instance-metadata=true --kubeconfig=C:\hpc\/var/lib/cpaw/kubeconfig.conf
invalid configuration: unable to read certificate-authority C:\hpc\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt for default due to open C:\hpc\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt: The system cannot find the path specified.`

The cluster is created using CAPI+CAPZ. The cloud-node-manager on windows fails a few times before it starts working. The container restarts 3-4 times with above error then it automatically starts working.
