### ISSUE TITLE
In-tree to Out-of-tree cpi migration in HA cluster

### ISSUE THREAD

**Issue by wangyuan0916** [kubernetes-sigs/cloud-provider-azure#2664]
We have kubernetes clusters with multi masters, with in-tree azure cpi deployed on them. We need to migrate these cluster to out-of-tree azure cpi when rolling upgrade to new k8s version. Are there any down time when upgrade? These clusters are HA clusters, we don't want down time during upgrade. Are there any docs about this? 

https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2664#tasklist-block-acf619c1-84a7-4209-886e-937aef9b739f

**Comment by bridgetkromhout** [comment]
Additional context: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2297#issuecomment-1319402166

**Comment by feiskyer** [comment]
Refer https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2297#issuecomment-1319402166: 

The suggested method is upgrading the out-of-tree components to a new version. But it should also be ok to upgrade them to the same version. Since CCM is an async controller running after apiserver, it should not break the HA of the cluster availability.
