### ISSUE TITLE
LoadBalancerSourceRanges: Multiple CIDRs for one NSG rule

### ISSUE THREAD

**Issue by gcs278** [kubernetes-sigs/cloud-provider-azure#4713]
### What would you like to be added:

Currently, if you set `spec.loadBalancerSourceRanges` to use multiple CIDRs, it will create 1 network security group (NSG) rule per CIDR. We need a mechanism in which we could specify `spec.loadBalancerSourceRanges` for 1 NSG rule with multiple CIDRs. 

### Why is this needed:

We need more than 1000 CIDRs. The [1000 NSG rule limit](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/azure-virtual-network-limits.md) also results in a limitation of 1000 CIDRs since one NSG rule is created for each CIDR. By associating the CIDRs with one NSG rule, the limit of CIDRS would effectively be increased to 4000.

### Design Ideas:

1. **Create rules with multiple CIDRs**

    This update involves transitioning from the creation of multiple NSG rules to the creation of a single rule with multiple CIDRs. Are there any drawbacks to combining rules, e.g. performance, limits, or management concerns? If there is some advantage to using separate rules, we could add an option for combining rules, such as a service annotation.

~~2. **Enable use of pre-created NSGs**~~

~~With this approach, the cluster admin would need to precreate the desired NSGs.  However, this approach would require another API field, such as a service annotation like AWS's [service.beta.kubernetes.io/aws-load-balancer-security-groups](https://aws.amazon.com/blogs/containers/network-load-balancers-now-support-security-groups/) service annotation.~~ **Edit**: I'm removing this idea as there was some confusion about NSGs. As far as I understand, NSGs are linked to subnets, and it seems illogical to me to provide your own NSG alongside a Service, as it would need to apply to the subnets, not the load balancer.

**Comment by MartinForReal** [comment]
Could you please try 
service.beta.kubernetes.io/azure-shared-securityrule annotation? https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/

**Comment by gcs278** [comment]
@MartinForReal thanks for the tip. Just tried it out. When using with `spec.loadBalancerSourceRanges`, that annotation groups the destination IP addresses (the frontend load balancer IP) if you have the same source:
![image](https://github.com/kubernetes-sigs/cloud-provider-azure/assets/4316443/9169a746-4c19-4d42-a8a7-e0af2b5d5c58)

Though that is helpful when you have multiple services with the same `spec.loadBalancerSourceRanges`, it still limits the number of  `spec.loadBalancerSourceRanges` to ~1000 CIDRs for a single service (due to NSG rule limitation). We are looking for solutions to get ~5000 CIDRs specified in the `spec.loadBalancerSourceRanges`.

One idea would be another new annotation like `service.beta.kubernetes.io/azure-shared-securityrule` that shares the source IP so the limit would be increased to 4000, such as:
![image](https://github.com/kubernetes-sigs/cloud-provider-azure/assets/4316443/4a5c240e-ba7d-4391-a630-dd15ac384c8c)

Or even better, the new annotation could enable cloud-azure-operator to have logic to group rules in such a way that would allow more than 4000 CIDR inputs. Our use case is targeting 5000 CIDRs, but we are currently limited to 1000.

**Comment by phealy** [comment]
@gcs278 You can't have 5k CIDRs specified in `loadBalancerSourceRanges` no matter how they're structured: any single network security group has a [maximum of 4,000 IP addresses and ranges specified for sources or destinations](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits?toc=%2Fazure%2Fvirtual-network%2Ftoc.json#azure-resource-manager-virtual-networking-limits:~:text=IP%20addresses%20and,4%2C000), and that limit is the total across all rules in the entire NSG.

@lodrem FYI for limit checking so that rules don't fail to apply.

**Comment by gcs278** [comment]
@phealy You are correct, my mistake. We are targeting maximizing the limit of `spec.loadBalancerSourceRanges` to 4000 CIDRs.

**Comment by phealy** [comment]
> @phealy You are correct, my mistake. We are targeting maximizing the limit of `spec.loadBalancerSourceRanges` to 4000 CIDRs.

I just wanted to make sure you were aware that that is not 4,000 per rule but it's 4000 total.

**Comment by elmiko** [comment]
we are talking about this issue at today's sig cloud provider meeting, might be good to get some discussion with @bridgetkromhout and @feiskyer , we will plan to discuss this again at the december 6 meeting if folks are around.

**Comment by MartinForReal** [comment]
When the svc is updated, how to delete orphaned rules?

**Comment by lodrem** [comment]
> When the svc is updated, how to delete orphaned rules?

- It should be easy to identify rules that have ‘svc.metadata.uid’ in their name.
- For the shared-security-rules, couldn’t we just clean up the destination addresses which are the same as the current implementation?

**Comment by gcs278** [comment]
@lodrem just to clarify: is suggestion applying to both `spec.loadBalancerSourceRanges` and the annotations (`service.beta.kubernetes.io/azure-allowed-ip-ranges`, `service.beta.kubernetes.io/azure-allowed-service-tags`)? Or just the annotations?

**Comment by lodrem** [comment]
> @lodrem just to clarify: is suggestion applying to both spec.loadBalancerSourceRanges and the annotations (service.beta.kubernetes.io/azure-allowed-ip-ranges, service.beta.kubernetes.io/azure-allowed-service-tags)? Or just the annotations?

@gcs278 Don’t try to use `spec.loadBalancerSourceRanges` and `service.beta.kubernetes.io/azure-allowed-service-tags` together. It won’t work. refer: https://github.com/kubernetes/kubernetes/issues/109575

1. To create a **IPRange** allow list, apply either `spec.loadBalancerSourceRanges` or `service.beta.kubernetes.io/azure-allowed-ip-range`.
2. To create a **ServiceTag** allow list, just apply `service.beta.kubernetes.io/azure-allowed-service-tags`.
3. To get both **ServiceTag** and **IPRange** on an allow list, you need to apply annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges` and `service.beta.kubernetes.io/azure-allowed-service-tags`.

**Comment by jwtty** [comment]
@lodrem  Have 4 questions:
1. For service tags, destination address contains both IPv4 and IPv6, is this allowed?
2. How to differentiate TCP and UDP? I don't see it from the rule naming.
3. I wonder if random UUID would be a good idea. It would be complex to write UTs and compare goal states and it does not convey any more information.
4. Not sure about shared rules... Do shared rules allow custom source IP ranges?

**Comment by lodrem** [comment]
> is the new security rule layout applying to spec.loadBalancerSourceRanges as well?

@gcs278 Yes!

**Comment by phealy** [comment]
Oh, one last note - in the error case, we should make sure that the deny rule isn't dropped - better to fail secure than fail open.

**Comment by phealy** [comment]
> Just to clarify, if we turned on the shared-security-rules (current implementation), it should create only 2 rules

Yes - I was comparing to the default, not shared. Good call to point that out!

**Comment by phealy** [comment]
> Yeah, we could do it, but it should be just for auditing. This data might not match the actual NSG rules. Imagine if something messes up after we’ve put the NSG rules in, and then we fail to update the status conditions. NSG rules are the source of truth.

Agreed, this is more for indicating what the calculated hash was to look up rules more easily when troubleshooting problems.

> It should result in <M IP family> * (<1 IP source> + <K service tags source>) * <2 protocols - TCP/UDP> * <N services> rules because it could only create 1 service tag and 1 IP family per rule.

Great point, I wasn't thinking about the fact that even with service tags we still have to have both the IPv4 and IPv6 **destination** addresses in different rules and also forgot that you can't put multiple service tags in a single rule like you can CIDR blocks.

**Comment by phealy** [comment]
OK, one last follow-on now that I've gotten the math through my head - would it make sense to make two more service tags annotations, for protocol specificity? That would allow you to say "I only want service tag access via IPv4 on this dual stack service."

- `service.beta.kubernetes.io/azure-allowed-service-tags`
- `service.beta.kubernetes.io/azure-allowed-service-tags-ipv4`
- `service.beta.kubernetes.io/azure-allowed-service-tags-ipv6`

I don't think it's worth the effort/additional annotations when there's an easy workaround - create two single stack services with different allow lists - but I wanted to propose it here.

**Comment by phealy** [comment]
Noticed one more thing:

> Besides, for the deny-all rule you mentioned, it could be named as cloud-provider-lb_deny-all_{ruleId}.

I think we could actually get down to a single deny-all rule for **all** service IPs and leave the rule ID out - after all, we've already allowed everything needed, so a single rule at the end that just does "deny all ports and protocols for all of these service IP address: <addresses>" would save rule slots. We don't need to be specific on anything.

**Comment by lodrem** [comment]
> would it make sense to make two more service tags annotations, for protocol specificity? That would allow you to say "I only want service tag access via IPv4 on this dual stack service."

Yeah, I’m curious though: what app “only want service tag access via IPv4 on this dual stack service.”? 

And I can’t think of any other way to label the service tag with the IP family, except maybe adding two more annotations or changing the existing one (either way, I’m good):

- `service.beta.kubernetes.io/azure-allowed-service-tags: "AzureCloud"`
Traffic from AzureCloud is allowed either via IPv4 or IPv6.
- `service.beta.kubernetes.io/azure-allowed-service-tags: "AzureCloud,AzureDatabricks/ipv4"` 
Traffic from AzureCloud is allowed either via IPv4 or IPv6, while AzureDatabricks only allows it via IPv4.
- `service.beta.kubernetes.io/azure-allowed-service-tags: "AzureCloud/ipv6,AzureDatabricks/ipv4"`
Traffic from AzureCloud is only allowed via IPv6, while AzureDatabricks only allows it via IPv4.

**Comment by phealy** [comment]
I thought about it more and talked to Jorge and I think saying "if you want to split service tags by family, use two single stack services" is good enough. Please ignore my previous comment on that :)

**Comment by lodrem** [comment]
# Final decision
Just to recap, if you’re new here, you can skip the above discussion.

## Goal state

1. It will be applied to both annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges` / `service.beta.kubernetes.io/azure-allowed-service-tags` and the spec setting `spec.loadBalancerSourceRanges`.

### Best case

If you’ve got 100 services running on TCP 80 and 443, all using the same **N** allowed IPv4 list, **M** allowed IPv6 list, and **K** service tags, you’ll actually only end up needing **2 + 2K** rules for all of them. 

That’s instead of the **200N + 200M + 200K** rules you’d need in the current setup or even the **2N + 2M + 2K** rules when shared-security-rules enabled.

### Worst case

All services have distinct allowed IP sets and allowed service tags. It would result in the creation of **<1 - IPv4 list> + <1 - IPv6 list> + 2 * <K - service tags>** rules per service compared to the **(<N - IPv4 list> + <M - IPv6 list> + 2 * <K - service tags>) * <X - dst ports>** rules per service in the current set up.

## Rule naming
#### prefix
use `k8s-azure` refer to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/788

#### rules
1. `k8s-azure-lb_allow_{ruleId}` allow access.
   `src` : `protocol` : `dst-ports` are fixed.
   The only editable field is `destination-addresses`.
3. `k8s-azure-lb_deny-all` deny access; only 1 rule would be created.
   All services share the same rule (`src` : `protocol` : `dst-ports` = `*` : `*` : `*`).
   The only editable field is `destination-addresses`.

#### {ruleId}
generated by `hash("<src-prefixes>-<protocol>-<dst-ports>")`
- `src-prefixes`: a list of IPs (from the same IP family) or a single service tag
- `protocol`: TCP / UDP / ANY (When service has the same TCP / UDP ports)
- `dst-port`: a list of service ports

It would result in `<M IP family> * (<1 IP source> + <K service tags source>) * <2 protocols - TCP/UDP> * <N services>` rules or `M * (1 + K) * 2` per service.

## Rule reconciliation
### EnsureLB/UpdateLB
1. Generate rule name and get the specific rule.
2. If the rule not found, create one.
5. If the rule found, update the rule destination addresses field.
6. Clean up the legacy rules for this LB service.

### DeleteLB
1. Generate rule name and get the specific rule.
2. If the rule not found, skip.
3. If the rule found, update the rule destination addresses field. Delete it if there’s no destination address left.
4. Clean up the legacy rules for this LB service.

## Error
1. When the number of rules exceeds 1k, it should throw an error message and emit an event.
2. When the number of IP ranges exceeds 4k, it should throw an error message and emit an event.

refer:
1. [Azure Networking limits](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits?toc=%2Fazure%2Fvirtual-network%2Ftoc.json#azure-resource-manager-virtual-networking-limits)

And if all our rules are built as shared, we would deprecate the annotation `service.beta.kubernetes.io/azure-shared-securityrule`.

If there are no other concerns, I’ll jump into coding. Thanks!
