### ISSUE TITLE
Categorize 404 error code instead of ignoring all of them

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#933]
#### What happened:

The 404 is ignored when [removing load balancer](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_loadbalancer.go#L185) because we don't want to block the service deletion if the end user proactively removes the azure resources. But sometimes the cluster autoscaler will trigger the deletion of VM/VMSS VM instances, and the cloud provider will return a 404 when decoupling the LB from the VM/VMSS VM. In this case, the 404 will be ignored and the corresponding load balancing resources, such as load balancing rules, probes and frontend IP configurations will not be cleaned up.

#### What you expected to happen:

The corresponding load balancing resources are cleaned up.

#### How to reproduce it (as minimally and precisely as possible):

When the svc deletion and the node scale-down are triggered at the same time.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nilo19** [comment]
A possible solution is to check the existence of the resource group before returning the 404 error. In this way, the resource group client should be added to the repo.

**Comment by nilo19** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/93962

**Comment by lzhecheng** [comment]
It may not be valid to check existence of resource group. The reason is that resources (LB, IP, etc.) can be in different resource groups and users can add new resources into LB related resource group. Existence of resource group cannot tell if a LB's related resources are successfully deleted or not.
I have a tentative approach for the issue. The basic idea is:
It is incorrect to check 403/404 error when calling `reconcileLoadBalancer()` inside `EnsureLoadBalancerDeleted()` because as long as a resource doesn't exist, `reconcileLoadBalancer()` will return immediately then other LB related resources are not handled yet.
Instead, 403/404 error should be checked at every `GetSomeResource()` inside `reconcileLoadBalancer()`. If it is a 403/404 error, then continue.
https://github.com/lzhecheng/cloud-provider-azure/commit/460639216faa45024ef305e3f7586108b064c085
Above commit is not fully checked or tested. It is just for presenting my idea.
Please correct me if anything is incorrect. @nilo19 @feiskyer

**Comment by feiskyer** [comment]
> Instead, 403/404 error should be checked at every GetSomeResource() inside reconcileLoadBalancer(). If it is a 403/404 error, then continue.
Yes, +1 for this.
